# Generated by Django 3.2.5 on 2021-07-29 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название активности')),
                ('calorie_content', models.IntegerField(verbose_name='Удельная калорийность')),
                ('unit', models.CharField(max_length=150, verbose_name='Единица измерения')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название блюда')),
                ('calorie_content', models.IntegerField(verbose_name='Удельная калорийность')),
                ('serving_weight', models.CharField(max_length=150, verbose_name='Масса по умольчанию')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('patronymic', models.CharField(default='', max_length=150, verbose_name='Отчество')),
                ('height', models.IntegerField(verbose_name='Рост')),
                ('weight', models.IntegerField(verbose_name='Вес')),
                ('age', models.IntegerField(verbose_name='Возраст')),
            ],
        ),
        migrations.CreateModel(
            name='PersonDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Время еды')),
                ('amount', models.IntegerField(verbose_name='Кол-во порций')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='calorie.dish')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='calorie.person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Время активности')),
                ('duration', models.IntegerField(verbose_name='Продолжитеьность активности')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='calorie.activity')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='calorie.person')),
            ],
        ),
    ]
