# Generated by Django 3.2.5 on 2021-07-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='unit',
            field=models.CharField(choices=[('km', 'КМ'), ('minute', 'минуту'), ('step', 'шаг')], max_length=150, verbose_name='Единица измерения'),
        ),
    ]
