# Generated by Django 3.2.5 on 2021-07-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0003_alter_activity_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dish',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personactivity',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='persondish',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
