# Generated by Django 3.2.5 on 2021-07-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0004_auto_20210729_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='serving_weight',
            field=models.IntegerField(verbose_name='Масса по умольчанию в граммах'),
        ),
        migrations.AlterField(
            model_name='personactivity',
            name='duration',
            field=models.IntegerField(verbose_name='Продолжительность активности'),
        ),
    ]
